server:
  port: 9999

spring:
  application:
    name: rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  sleuth:
    messaging:
      rabbit:
        enabled: true
log:
  home: /data/logs